DELETE FROM order_events;
DELETE FROM orders;
DELETE FROM sweetbook_uploaded_assets;
DELETE FROM sweetbook_books;
DELETE FROM book_snapshot_items;
DELETE FROM book_snapshots;
DELETE FROM card_entries;
DELETE FROM day_cards;
DELETE FROM uploaded_assets;
DELETE FROM couples;
DELETE FROM users;
ALTER TABLE day_cards ALTER COLUMN id RESTART WITH 1;
ALTER TABLE card_entries ALTER COLUMN id RESTART WITH 1;
ALTER TABLE book_snapshots ALTER COLUMN id RESTART WITH 1;
ALTER TABLE book_snapshot_items ALTER COLUMN id RESTART WITH 1;
ALTER TABLE sweetbook_books ALTER COLUMN id RESTART WITH 1;
ALTER TABLE sweetbook_uploaded_assets ALTER COLUMN id RESTART WITH 1;
ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE order_events ALTER COLUMN id RESTART WITH 1;
