CREATE TABLE users (
  id VARCHAR(100) PRIMARY KEY,
  auth_provider VARCHAR(50) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE couples (
  id VARCHAR(100) PRIMARY KEY,
  creator_user_id VARCHAR(100) NOT NULL,
  partner_user_id VARCHAR(100) NULL,
  invite_code VARCHAR(30) NOT NULL UNIQUE,
  anniversary_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  accepted_at TIMESTAMP WITH TIME ZONE NULL,
  unlinked_at TIMESTAMP WITH TIME ZONE NULL,
  CONSTRAINT fk_couples_creator_user FOREIGN KEY (creator_user_id) REFERENCES users (id),
  CONSTRAINT fk_couples_partner_user FOREIGN KEY (partner_user_id) REFERENCES users (id)
);

CREATE INDEX idx_couples_creator_user_id ON couples (creator_user_id);
CREATE INDEX idx_couples_partner_user_id ON couples (partner_user_id);
CREATE INDEX idx_couples_status ON couples (status);

CREATE TABLE day_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  couple_id VARCHAR(100) NOT NULL,
  local_date DATE NOT NULL,
  state VARCHAR(20) NOT NULL,
  close_at_utc TIMESTAMP WITH TIME ZONE NULL,
  closed_at TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_day_cards_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
  CONSTRAINT uq_day_cards_couple_date UNIQUE (couple_id, local_date)
);

CREATE INDEX idx_day_cards_couple_id ON day_cards (couple_id);
CREATE INDEX idx_day_cards_local_date ON day_cards (local_date);

CREATE TABLE card_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_card_id BIGINT NOT NULL,
  user_id VARCHAR(100) NOT NULL,
  emotion_code VARCHAR(30) NOT NULL,
  memo VARCHAR(2000) NULL,
  photo_url VARCHAR(2000) NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_card_entries_day_card FOREIGN KEY (day_card_id) REFERENCES day_cards (id) ON DELETE CASCADE,
  CONSTRAINT fk_card_entries_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT uq_card_entries_day_card_user UNIQUE (day_card_id, user_id)
);

CREATE INDEX idx_card_entries_day_card_id ON card_entries (day_card_id);
CREATE INDEX idx_card_entries_user_id ON card_entries (user_id);
