CREATE TABLE book_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  couple_id VARCHAR(100) NOT NULL,
  status VARCHAR(30) NOT NULL,
  window_start_date DATE NOT NULL,
  window_end_date DATE NOT NULL,
  recorded_days INT NOT NULL,
  selected_item_count INT NOT NULL,
  build_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  build_completed_at TIMESTAMP WITH TIME ZONE NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_book_snapshots_couple FOREIGN KEY (couple_id) REFERENCES couples (id)
);

CREATE INDEX idx_book_snapshots_couple_id ON book_snapshots (couple_id);
CREATE INDEX idx_book_snapshots_status ON book_snapshots (status);

CREATE TABLE book_snapshot_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL,
  day_card_id BIGINT NOT NULL,
  local_date DATE NOT NULL,
  my_entry_json TEXT NULL,
  partner_entry_json TEXT NULL,
  photo_asset_id VARCHAR(100) NULL,
  page_order INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_book_snapshot_items_snapshot FOREIGN KEY (snapshot_id) REFERENCES book_snapshots (id) ON DELETE CASCADE,
  CONSTRAINT fk_book_snapshot_items_day_card FOREIGN KEY (day_card_id) REFERENCES day_cards (id),
  CONSTRAINT fk_book_snapshot_items_photo_asset FOREIGN KEY (photo_asset_id) REFERENCES uploaded_assets (id)
);

CREATE INDEX idx_book_snapshot_items_snapshot_id ON book_snapshot_items (snapshot_id);
