CREATE TABLE sweetbook_books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL UNIQUE,
  sweetbook_book_uid VARCHAR(100) NULL UNIQUE,
  book_spec_id VARCHAR(100) NOT NULL,
  template_id VARCHAR(100) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_request_id VARCHAR(150) NOT NULL,
  finalized_at TIMESTAMP WITH TIME ZONE NULL,
  failure_code VARCHAR(100) NULL,
  failure_message VARCHAR(2000) NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_sweetbook_books_snapshot FOREIGN KEY (snapshot_id) REFERENCES book_snapshots (id)
);

CREATE TABLE sweetbook_uploaded_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sweetbook_book_id BIGINT NOT NULL,
  uploaded_asset_id VARCHAR(100) NOT NULL,
  sweetbook_file_name VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL,
  uploaded_at TIMESTAMP WITH TIME ZONE NULL,
  failure_code VARCHAR(100) NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_sweetbook_uploaded_assets_book FOREIGN KEY (sweetbook_book_id) REFERENCES sweetbook_books (id) ON DELETE CASCADE,
  CONSTRAINT fk_sweetbook_uploaded_assets_asset FOREIGN KEY (uploaded_asset_id) REFERENCES uploaded_assets (id)
);

CREATE INDEX idx_sweetbook_uploaded_assets_book_id ON sweetbook_uploaded_assets (sweetbook_book_id);
