CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL,
  ordering_user_id VARCHAR(100) NOT NULL,
  recipient_name VARCHAR(100) NOT NULL,
  recipient_phone VARCHAR(20) NOT NULL,
  postal_code VARCHAR(10) NOT NULL,
  address1 VARCHAR(200) NOT NULL,
  address2 VARCHAR(200) NULL,
  shipping_memo VARCHAR(200) NULL,
  status VARCHAR(30) NOT NULL,
  sweetbook_order_uid VARCHAR(100) NULL UNIQUE,
  sweetbook_order_status_code INT NULL,
  sweetbook_order_status_display VARCHAR(100) NULL,
  tracking_carrier VARCHAR(30) NULL,
  tracking_number VARCHAR(100) NULL,
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
  submitted_at TIMESTAMP WITH TIME ZONE NULL,
  completed_at TIMESTAMP WITH TIME ZONE NULL,
  failure_code VARCHAR(100) NULL,
  failure_message VARCHAR(2000) NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_orders_snapshot FOREIGN KEY (snapshot_id) REFERENCES book_snapshots (id),
  CONSTRAINT fk_orders_ordering_user FOREIGN KEY (ordering_user_id) REFERENCES users (id)
);

CREATE INDEX idx_orders_snapshot_id ON orders (snapshot_id);
CREATE INDEX idx_orders_ordering_user_id ON orders (ordering_user_id);
CREATE INDEX idx_orders_status ON orders (status);

CREATE TABLE order_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NULL,
  event_type VARCHAR(100) NOT NULL,
  dedupe_key VARCHAR(150) NOT NULL UNIQUE,
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_order_events_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX idx_order_events_order_id ON order_events (order_id);
